name: tls-certificate-heartbeat

role:
  apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

schedule: "*/15 * * * *"  # every 15 minutes

expiryThresholdSeconds: 604800  # 7 days

# object to contain info on which cluster certificates to check, with following format
namespaces:
  default:
    certificates:
    - secretName: accurx-certificate
      heartBeatUrl: https://accurx.com/heartbeat/1234
#namespaces: []
