{{- $expireThresholdSeconds := 604800 }}
{{- $heartbeatCronJobImage := "bitnami/kubectl:1.25.2-debian-11-r3" }}
{{- $schedule := .Values.schedule }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{.Values.name}}
  namespace: {{default "cronjobs" .Values.namespace}}
spec:
  schedule: "{{ $schedule }}"
  jobTemplate:
    spec:
      suspend: {{default false .Values.suspend}}
      template:
        {{- if .Values.labels }}
        metadata:
          labels:
            {{ .Values.labels | toYaml }}
        {{- end }}
        spec:
          {{- if .Values.role }}
          serviceAccountName: "{{.Values.name}}-cron-sa"
          {{- end }}
          containers:
            - name: {{.Values.name}}
              image: {{ $heartbeatCronJobImage }}
              command: [ "/bin/bash", "-c" ]
              args:
              - > 
              {{- range $namespace, $value := .Values.namespaces }}
                {{- range $certificate := $value.certificates }}
                  {{- if $certificate.heartBeatUrl }}
                /certificates_configmap/internal-certificate-heartbeat.sh {{ $expireThresholdSeconds }} {{ $certificate.secretName }} {{ $certificate.heartBeatUrl }} "{{ ternary $certificate.secretJsonpath "" (hasKey $certificate "secretJsonpath") }}"
                  {{- end }}
                {{- end }}
              {{- end }}
              volumeMounts:
                - name: configmap
                  mountPath: /certificates_configmap
                  readOnly: false
          volumes:
            - name: configmap
              configMap:
                name: internal-certificate-heartbeat
                defaultMode: 0777
          restartPolicy: OnFailure

